### ISSUE TITLE
Get all the values, key from value

### ISSUE THREAD

**Issue by shahreyar-abeer** [r-lib/fastmap#14]
Is it possible to-
1. Get all the values?
2. Get key(s) given a value?

**Comment by wch** [comment]
Yes, though it won't be as fast as the reverse operations. For the first, you can use `m$mget(m$keys())`. That will return a named list. For the second, I think you'd have to iterate through that list to search for the value, then get the corresponding name for that index.

**Comment by shahreyar-abeer** [comment]
Thanks for that.

**Comment by wch** [comment]
I just remembered that you can use `m$as_list()` to get a named list. That's simpler and probably faster than `m$mget(m$keys())`.

**Comment by shahreyar-abeer** [comment]
Thanks. I did do that.
Is there any way to update the values except m$set()?

**Comment by wch** [comment]
You can use `m$mset()`. This stuff is in the documentation, which can see with `?fastmap`, or here:
https://r-lib.github.io/fastmap/reference/fastmap.html

**Comment by shahreyar-abeer** [comment]
Okay, thanks for that.
