### ISSUE TITLE
Installation fails during package compilation due to unnamed symbol

### ISSUE THREAD

**Issue by ilyaZar** [r-lib/fastmap#31]
The following is from `remotes::install_github("git@github.com:r-lib/fastmap.git")` but `install.packages("fastmap")` produces the same:

```r
Downloading GitHub repo r-lib/fastmap@HEAD
✔  checking for file ‘/tmp/RtmpyB7Jnd/remotes59a392a39abf3/r-lib-fastmap-cc35820/DESCRIPTION’ ...
─  preparing ‘fastmap’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘fastmap_1.1.1.9000.tar.gz’
   
Installing package into ‘/home/iz/Dropbox/libraries/R/4.0’
(as ‘lib’ is unspecified)
* installing *source* package ‘fastmap’ ...
** using staged installation
** libs
g++ -std=gnu++14 -I"/usr/share/R/include" -DNDEBUG -Ilib/    -g -O0 -fpic  -g -O0 -c fastmap.cpp -o fastmap.o
gcc -I"/usr/share/R/include" -DNDEBUG -Ilib/     -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-a3XuZ5/r-base-4.2.2.20221110=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c init.c -o init.o
g++ -std=gnu++14 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o fastmap.so fastmap.o init.o -L/usr/lib/R/lib -lR
installing to /home/iz/Dropbox/libraries/R/4.0/00LOCK-fastmap/00new/fastmap/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘fastmap’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/iz/Dropbox/libraries/R/4.0/00LOCK-fastmap/00new/fastmap/libs/fastmap.so':
  /home/iz/Dropbox/libraries/R/4.0/00LOCK-fastmap/00new/fastmap/libs/fastmap.so: undefined symbol: _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9Rf_lengthEv
Error: loading failed
Execution halted
```

<details closed>
<summary>Sessioninfo</summary>
<br>
<pre>
> sessioninfo::session_info()
─ Session info ─────────────────────────────────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.2.2 Patched (2022-11-10 r83330)
 os       Linux Mint 20
 system   x86_64, linux-gnu
 ui       RStudio
 language en_US
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Berlin
 date     2023-03-02
 rstudio  2022.07.2+576 Spotted Wakerobin (desktop)
 pandoc   NA

─ Packages 
 package     * version    date (UTC) lib source
 attempt       0.3.1      2020-05-03 [1] CRAN (R 4.0.2)
 brio          1.1.3      2021-11-30 [1] CRAN (R 4.2.1)
 cli           3.6.0      2023-01-09 [1] CRAN (R 4.2.2)
 config        0.3.1      2020-12-17 [1] CRAN (R 4.0.3)
 desc          1.4.2      2022-09-08 [1] CRAN (R 4.2.2)
 digest        0.6.31     2022-12-11 [1] CRAN (R 4.2.2)
 ellipsis      0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
 fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.0.4)
 fs          * 1.6.1      2023-02-06 [1] CRAN (R 4.2.2)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.1.3)
 golem       * 0.3.5.9001 2023-03-02 [1] local
 htmltools     0.5.4      2022-12-07 [1] CRAN (R 4.2.2)
 httpuv        1.6.9      2023-02-14 [1] CRAN (R 4.2.2)
 later         1.3.0      2021-08-18 [1] CRAN (R 4.1.1)
 lifecycle     1.0.3      2022-10-07 [1] CRAN (R 4.2.1)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.1)
 mime          0.12       2021-09-28 [1] CRAN (R 4.1.1)
 pkgload       1.3.2      2022-11-16 [1] CRAN (R 4.2.2)
 promises      1.2.0.1    2021-02-11 [1] CRAN (R 4.0.4)
 purrr         1.0.1      2023-01-10 [1] CRAN (R 4.2.2)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp          1.0.10     2023-01-22 [1] CRAN (R 4.2.2)
 rlang         1.0.6      2022-09-24 [1] CRAN (R 4.2.1)
 rprojroot     2.0.3      2022-04-02 [1] CRAN (R 4.1.3)
 rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.2)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.1.3)
 shiny         1.7.4      2022-12-15 [1] CRAN (R 4.2.2)
 testthat    * 3.1.4      2022-04-26 [1] CRAN (R 4.2.1)
 usethis       2.1.6      2022-05-25 [1] CRAN (R 4.2.1)
 vctrs         0.5.2      2023-01-23 [1] CRAN (R 4.2.2)
 withr       * 2.5.0      2022-03-03 [1] CRAN (R 4.1.3)
 xtable        1.8-4      2019-04-21 [1] CRAN (R 4.0.2)
 yaml          2.3.7      2023-01-23 [1] CRAN (R 4.2.2)

 [1] /home/iz/Dropbox/libraries/R/4.0
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library

</pre>
</details>

**Comment by wch** [comment]
I think the problem is that the compiler is expecting to see `Rf_` prefix for `Rf_length`, instead of just `length`. (See https://colinfay.me/writing-r-extensions/the-r-api-entry-points-for-c-code.html for a bit more info.)

In the Makevars file, it's setting `PKG_CXXFLAGS=-DR_NO_REMAP`, and that flag should show up in your compilation command line, but I don't see it there. Are you setting customized `CXX_FLAGS` in a personal Makevars file?
https://github.com/r-lib/fastmap/blob/cc358209f41a17bf00ff69ec6b9746ff3a4399e5/src/Makevars#L1-L2

**Comment by ilyaZar** [comment]
Thanks for the fast reply!

Yes, for debugging purposes I tend to set:

```
CXXFLAGS= -g -O0
PKG_CXXFLAGS= -g -O0
```

Installation works when I comment out `PKG_CXXFLAGS= -g -O0` so it is exactly that line.

**Comment by wch** [comment]
Great! I think you should avoid setting `PKG_CXXFLAGS`, since that is meant to be set inside of packages.
