### ISSUE TITLE
Consider switching back to `std::map`

### ISSUE THREAD

**Issue by wch** [r-lib/fastmap#8]
fastmap currently uses `std::unordered_map`. Because of this, if you call `m$keys()` or `m$as_list()`, the order is arbitrary and can differ across platforms. This means that code that behaves one way on one computer can behave a different way on another computer. In Shiny, for example, this means that reactives might fire in different orders on different computers: https://github.com/rstudio/shiny/issues/2466#issuecomment-497904851

With environments, the order is arbitrary, but at least it is consistent across platforms.

We should consider replacing the `std::unordered_map` with either `std::map`, or some other implementation that behaves consistently across platforms.

**Comment by dselivanov** [comment]
I think this issue is related to shiny, not fastmap. Shiny should not rely
on undefined/non-guaranteed behavior of the hash map.

сб, 1 июн. 2019 г., 6:48 Winston Chang <notifications@github.com>:

**Comment by wch** [comment]
The problem is that any program or analysis that happens to use order can have different behavior on different machines, or even on the same machine over time. This can cause problems with the reproducibility of a data analysis. It's also a problem if there's R code that behaves one way on development machine and another way on a production server. Debugging these cases can be very difficult, especially for R users who don't expect differences in behavior across platforms.

With C++ code, it's common to have differences across platforms, but with R code, that is very unusual. One of the reasons for using a high-level language like R is to not have to deal with things like that. In this case, I don't think the performance benefit is worth exposing users to this.

**Comment by dselivanov** [comment]
There are different users and it is always better to have all the options.
Mb then we should not shy explicitly mimic c++ maps and have 2 classes -
map and unordred_map? This won't be difficult - one R superclass can
implement all the functionality and subclasses will just implement proper
constructors.

сб, 1 июн. 2019 г., 16:46 Winston Chang <notifications@github.com>:
